### PR TITLE
Implemented a more efficient route to the same destination!

### PR DESCRIPTION
**Pull request by istx25**

### CODE REVIEW

**Comment by alikaragoz** [comment]
Wow is it that slow to use `pow` ?

**Comment by istx25** [comment]
I am at a hackathon that Apple sponsored and received the opportunity to talk to an iOS engineer and he suggested the change. :sweat_smile: Seems like it is more efficient.

**Comment by alikaragoz** [comment]
Thank you for the information, hope the hackathon went well ;)

**Comment by alikaragoz** [comment]
Sorry closed the pull request instead of merging :(
Can you please re-open it ?

**Comment by alikaragoz** [comment]
Managed to re-open it :+1:

**Comment by alikaragoz** [comment]
For information there was a parenthesis issue, it's fixed now. You might wan to pull the last changes.

**Comment by istx25** [comment]
Thanks! :heart:

**Pull request merged**
